name: Mirroring to private Gitlab repository

on:
  workflow_run:
    workflows: ["Dry run assembleRelease to Bintray"]
    branches: [develop]
    types:
      - completed
      - requested

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: 'git@gitlab.com:sampingan-mobile/dynamic-ui.git'
          GIT_USERNAME: "mochadwi"
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_PUBLIC_KEY: ${{ secrets.GIT_SSH_PUBLIC_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
          DEBUG: "true"
          PUSH_ALL_REFS: "false"
